# This file should ensure the existence of records required to run the application in every environment (production,
# development, test). The code here should be idempotent so that it can be executed at any point in every environment.
# The data can then be loaded with the bin/rails db:seed command (or created alongside the database with db:setup).
#
# Example:
#
#   ["Action", "Comedy", "Drama", "Horror"].each do |genre_name|
#     MovieGenre.find_or_create_by!(name: genre_name)
#   end
home = Home.create({
  description: "Looking for a beautiful main home with RV area plus an ADU/back house for your in-laws? The permitted ADU measures 20 x 25 feet for a total of 500 square feet with a ¼ bathroom, separate AC/heat & electrical panel! It is currently being used an awesome workshop & could also work as an art studio, extra storage – you name it. The main home offers a spacious single-story design with 4 bedrooms, 2 bathrooms, vaulted ceilings, ceiling fan lights & plenty of wall space for mirrors & photos. You will LOVE the upgrades throughout, including dual pane windows, plantation shutters, and tip-out drawer storage in the kitchen and bathrooms. The formal dining room features built-in cabinets perfect for display items and a buffet counter. The spacious family room features a fireplace and sliding glass door to the patio. More storage space in the hallway & kitchen with recessed lighting, Corian® style counter tops and stainless steel appliances. In the master bedroom, you have an ensuite bathroom with double sinks & ample cabinet space for bedding & towels. The 2nd bathroom also offers double sinks & access to the patio. Convenient indoor laundry area. About 3 years ago the owners replaced the water heater and HVAC with added vents for good circulation. Last year, the exterior of the home was given a new coat of paint. Enjoy the backyard with a citrus tree, mature shade tree, lawn area & spacious wood patio cover with 2 ceiling fan lights! This property is north of the 210 Freeway with an open view & gate access to Beryl Park - imagine how fun & easy it would be to walk your dogs & take the kids to the park! The front yard offers water-wise areas including the mow strip. Take a close look at this one-of-a-kind property in Alta Loma!", year_built: 1971, square_feet: 9990, bedrooms: 4, bathrooms: 2, floors: 1, availability: "yes", address: "8815 Alta Loma Dr, Alta Loma, CA 91701", price: 825000,
})
