# This file should ensure the existence of records required to run the application in every environment (production,
# development, test). The code here should be idempotent so that it can be executed at any point in every environment.
# The data can then be loaded with the bin/rails db:seed command (or created alongside the database with db:setup).
#
# Example:
#
#   ["Action", "Comedy", "Drama", "Horror"].each do |genre_name|
#     MovieGenre.find_or_create_by!(name: genre_name)
#   end
home = Home.create({
  description: "Looking for a beautiful main home with RV area plus an ADU/back house for your in-laws? The permitted ADU measures 20 x 25 feet for a total of 500 square feet with a ¼ bathroom, separate AC/heat & electrical panel! It is currently being used an awesome workshop & could also work as an art studio, extra storage – you name it. The main home offers a spacious single-story design with 4 bedrooms, 2 bathrooms, vaulted ceilings, ceiling fan lights & plenty of wall space for mirrors & photos. You will LOVE the upgrades throughout, including dual pane windows, plantation shutters, and tip-out drawer storage in the kitchen and bathrooms. The formal dining room features built-in cabinets perfect for display items and a buffet counter. The spacious family room features a fireplace and sliding glass door to the patio. More storage space in the hallway & kitchen with recessed lighting, Corian® style counter tops and stainless steel appliances. In the master bedroom, you have an ensuite bathroom with double sinks & ample cabinet space for bedding & towels. The 2nd bathroom also offers double sinks & access to the patio. Convenient indoor laundry area. About 3 years ago the owners replaced the water heater and HVAC with added vents for good circulation. Last year, the exterior of the home was given a new coat of paint. Enjoy the backyard with a citrus tree, mature shade tree, lawn area & spacious wood patio cover with 2 ceiling fan lights! This property is north of the 210 Freeway with an open view & gate access to Beryl Park - imagine how fun & easy it would be to walk your dogs & take the kids to the park! The front yard offers water-wise areas including the mow strip. Take a close look at this one-of-a-kind property in Alta Loma!", year_built: 1971, square_feet: 9990, bedrooms: 4, bathrooms: 2, floors: 1, availability: "yes", address: "8815 Alta Loma Dr, Alta Loma, CA 91701", price: 825000,
})
home = Home.create({
  description: "Welcome Home:  where luxury meets functionality in this recently remodeled single-level ranch-style home. Boasting a prime location on a large corner lot, this property offers a host of features that make it truly exceptional. As you approach, the professionally landscaped front and back yards immediately catch your eye. Drought-tolerant sod, automatic sprinkler system, and mature fruit trees, including avocado, oranges, lime, and lemon, contribute to the lush and vibrant exterior. A front yard sitting area surrounded by a privacy hedge welcomes you, secured by custom security iron doors with a unique screen feature. Step inside, and you'll discover meticulous attention to detail and a luxurious remodel that exudes quality and professional design. Wood-look tile flows seamlessly throughout the home, creating a warm and inviting atmosphere. The open-concept living room, complete with a gas fireplace, sets the stage for comfortable living. The gourmet kitchen is a chef's dream, featuring granite countertops, a large island with a sitting area, and Kitchen Aid appliances throughout. Dual ovens, a warming drawer for slow cooking, a griddle stove top, and a 48-bottle dual wine cabinet make this kitchen a culinary haven. Ample cabinet space ensures that everything has its place. The hall bathroom is a haven of relaxation, equipped with a light-up makeup mirror, a rain head shower, and a hydrotherapy tub. Meanwhile, the master bathroom boasts a Vichy spa-like shower that will leave you feeling pampered, reminiscent of a 5-star Resort Spa experience.   The backyard is a delightful space for family gatherings under the covered patio or around the firepit, where you can enjoy scenic mountain views. RV parking is a breeze, with a secure gated area next to the two-car garage, complete with an automatic opener. Washer, dryer, and an extra refrigerator are included for added convenience. This home is not just about luxury but also security. A hard-wired security system with outdoor cameras offers peace of mind, and the finger-touch access from your phone ensures easy control even when you're away. Located in a quiet neighborhood within walking distance to Alta Loma's excellent schools from Elementary to High School, this property offers a convenient lifestyle with quick freeway access and a nearby bike path for leisurely strolls.  Whether you're looking for a dream home or a sound investment for rental income, 7064 Slema Ave is a must-see.", year_built: 1964, square_feet: 1570, bedrooms: 3, bathrooms: 2, floors: 1, availability: "yes", address: "7064 Selma Ave, Alta Loma, CA 91701", price: 795000,
})
